### ISSUE TITLE
Es el jar correcto el que se especifica en el dockerfile?

### ISSUE THREAD

**Issue by TheTechOddBug** [deors/workshop-pipelines#2]
En este caso, ¿la aplicación es deors-demos-java-pipeline.jar o hackersweek6-workshop-pipelines-1.0-SNAPSHOT?

https://github.com/deors/workshop-pipelines-hackersweek6/blob/2c7fa2bf32e15c97087064e25270d087a4e2ad53/Dockerfile#L4

**Comment by deors** [comment]
Está mal efectivamente. PR? 😉
